const Portfolio_data = [
  {
    id: 10,
    category: "AUTHORED",
    totalLike: "600",
    title: "Woman Thou Art Worthy",
    image: "./img/Portfolio/woman thou art worthy.png",
    downloadLink: "https://www.amazon.com/Woman-thou-worthy-Winifred-Liam-ebook/dp/B094DZ9DRC/ref=sr_1_1?crid=3T8F1X6VHIQ2X&keywords=Woman+thou+art+worthy&qid=1647357828&s=digital-text&sprefix=woman+thou+art+worthy%2Cdigital-text%2C253&sr=1-1",
  },
  {
    id: 1,
    category: "AUTHORED",
    totalLike: "600",
    title: "Deck The Halls ",
    image: "./img/Portfolio/deckthehalls.png",
    downloadLink: "https://www.amazon.com/Deck-Halls-Naija-Christmas-Anthology-ebook/dp/B09P17NZ42",
  },
  {
    id: 2,
    category: "AUTHORED",
    totalLike: "750",
    title: "Ineffable",
    image: "./img/Portfolio/INEFFABLE.jpg",
    downloadLink: "/IneffablE.epub",
  },
  {
    id: 3,
    category: "ARTICLE",
    totalLike: "630",
    title: "NFT Play-To-Win Project",
    image: "./img/Portfolio/nft_image.png",
    downloadLink: "/Article on NFT_play_to_earn project.docx",
  },
  {
    id: 4,
    category: "GUIDE",
    totalLike: "360",
    title: "Basic IT Support Guide",
    image: "./img/Portfolio/it_support.png",
    downloadLink: "/Basic IT support Training.pdf",
  },
  {
    id: 5,
    category: "GUIDE",
    totalLike: "280",
    title: "Dash Diet - Ultimate Guide to Weight Loss and Healthy Living",
    image: "./img/Portfolio/weight_loss_guide.PNG",
    downloadLink:
      "/DASH DIET- ULTIMATE GUIDE TO WEIGHT LOSS AND HEALTHY EATING.pdf",
  },
  {
    id: 6,
    category: "ARTICLE",
    totalLike: "690",
    title: "KitoGenic Diet",
    image: "./img/Portfolio/keto.png",
    downloadLink: "/Ketogenic Diet.docx",
  },
];
export default Portfolio_data;
